### ISSUE TITLE
Cannot find module './node_natives/@serialport/bindings-cpp.native.cjs'

### ISSUE THREAD

**Issue by kingyue737** [vite-plugin/vite-plugin-native#13]
I tried this plugin but the built app throw the following error:
```
Uncaught Exception:
Error: Cannot find module './node_natives/@serialport/bindings-cpp.native.cjs'
Require stack:
D:\release\0.0.1\win-unpacked\resources\app.asar\dist-electron\main...
at Module._resolveFilename (node:internal/modules/cjs/loader: 1 1 52: 15)
at s._resolveFilename (node:electron/js2c/browser_init:2: 121381)
at Module._load
at c._load (node 17025)
at Module.require (node: internal/modules/cjs/loader:1240: 19)
at require 18)
at
at Module._compile (node:internal/modules/cjs/loader: 1373: 14)
at Module._extensions.js (node: internal/modules/cjs/loader:1432: 10)
at Module.load
```

Platform: Windows

Any help is appreciated

**Comment by kingyue737** [comment]
![image](https://github.com/user-attachments/assets/3175aef2-6090-43d0-9d07-ca50f2a3fef3)
No file named `@serialport/bindings-cpp.native.cjs` is generated

**Comment by kingyue737** [comment]
I found the cause. My config was `native({})`. But I just found `webpack` and `forceCopyIfUnbuilt` cannot be omitted here while the documentation says that `forceCopyIfUnbuilt` is `true` by default.
```ts
native({ forceCopyIfUnbuilt: true, webpack: {} })
```

But now comes another issue, the generated path in `bindings-cpp.native.cjs` is very strange:
```
// This is a native module that cannot be built correctly.
module.exports = require("../D:\Solutions\rho-meter\dist-electron\node_natives\node_modules\@serialport\bindings-cpp");
```

It seems to be a "relative-absolute" path and the backslash `\` in the path will cause error on windows.

**Comment by kingyue737** [comment]
Found a workaround without this plugin.

1. Tell Rollup to ignore dynamic require

```diff
build: [
      {
        vite: {
          plugins: isDev ? [notBundle()] : undefined,
          build: {
            minify: isProd,
+           commonjsOptions: {
+            ignoreDynamicRequires: true,
+         },
            lib: {
              entry: 'electron/main.ts',
              fileName: 'main',
              formats: ['cjs'],
            },
          },
        },
      },
]
```

2. Copy the required `.node` file to bundle via `electron-builder`
```diff
{
  "$schema": "node_modules/app-builder-lib/scheme.json",
  "asar": true,
  "directories": {
    "output": "release/${version}"
  },
  "files": [
    "dist-electron",
    ".output/**/*",
    "!node_modules/**/*"
  ],
  "electronLanguages": ["zh-CN"],
  "win": {
    "icon": "dist/favicon.ico",
+  "files": [
+    {
+        "from": "node_modules/@serialport/bindings-cpp/prebuilds/win32-x64",
+        "to": "prebuilds/win32-x64"
+    }
+   ],
    "target": [
      {
        "target": "nsis",
        "arch": ["x64"]
      }
    ]
  },
}
```

**Comment by yejimeiming** [comment]
> I found the cause. My config was `native({})`. But I just found `webpack` and `forceCopyIfUnbuilt` cannot be omitted here while the documentation says that `forceCopyIfUnbuilt` is `true` by default.
> 
> ```ts
> native({ forceCopyIfUnbuilt: true, webpack: {} })
> ```
> 
> But now comes another issue, the generated path in `bindings-cpp.native.cjs` is very strange:
> 
> ```
> // This is a native module that cannot be built correctly.
> module.exports = require("../D:\Solutions\rho-meter\dist-electron\node_natives\node_modules\@serialport\bindings-cpp");
> ```
> 
> It seems to be a "relative-absolute" path and the backslash `\` in the path will cause error on windows.

Okay! It's really a BUG in Windows, thanks for you feedback! I'll try to fix it in next version.
